movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='intex'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add'),
    path('update/<int:id>/',views.edit_movie,name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

movie_project/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    dis=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to="gallery")
    def __str__(self):
        return self.name

movie_project/movieapp/forms.py
from django import forms
from .models import Movie

class movie_form(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','dis','year','img']

movie_project/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .forms import movie_form
from . models import Movie
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }

    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'det':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        dis=request.POST.get('dis')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,dis=dis,year=year,img=img)
        movie.save()
        return redirect('/')
    return render(request,'add.html')
def edit_movie(request, id):
    movie=Movie.objects.get(id=id)
    form=movie_form(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':movie,'form':form})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movie_project/templates/add.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter the movie name"><br>
  <input type="text" name="dis" placeholder="enter the discription"><br>
  <input type="text" name="year" placeholder="enter the movie year"><br>
  <input type="file" name="img"><br>
  <input type="submit">


</form>

movie_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head></nav>

    <meta charset="UTF-8">
    <title>welcom</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
    </nav>
  {% block body %}
  {% endblock %}
  </body>
</html>

movie_project/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you sure to delete this movie
  <input type="submit">

</form>

movie_project/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{det.img.url}}"width="300" height="400">
        </div>
        <div class="col-md-6">
             <h2>{{det.name}}</h2>
        <h5>{{det.dis}}</h5>
        <h6>{{det.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' det.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' det.id %}">delete</a>

        </div>


    </div>
</div>
        {% endblock %}

movie_project/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
<h1 style="text-align:center;color:red;font-family:Fantasy;">Movies</h1>
<div class="container">
    <div class="row">
        {%for i in movie_list%}
        <div class="col-md-4">
            <div class="card" style="width: 20rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="350px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.dis}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Show</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>

<a class="btn btn-warning" href="{% url 'movieapp:add'%}">add</a>
{% endblock %}